const ruhEsinImages = {
  ruhesinlogo: require('../../src/assets/images/RuhEsinLogo.png'),
  body: require('../../src/assets/images/Body.png'),
  redLove: require('../../src/assets/images/RedLove.png'),
  slideBG: require('../../src/assets/images/SlideBG.png'),
  backBtn: require('../../src/assets/images/backBtn.png'),
  info: require('../../src/assets/images/info.png'),
  ilisievreni: require('../../src/assets/images/iliskievreni.png'),
  list: require('../../src/assets/images/list.png'),
  search: require('../../src/assets/images/search.png'),
  chat: require('../../src/assets/images/chat.png'),
  yinyang: require('../../src/assets/images/yinyang.png'),
  alert: require('../../src/assets/images/alert.png'),
  person: require('../../src/assets/images/person.png'),
  location: require('../../src/assets/images/location.png'),
  heart: require('../../src/assets/images/heart.png'),
  ellipse70: require('../../src/assets/images/ellipse70.png'),
  ellipse90: require('../../src/assets/images/ellipse90.png'),
  girl1: require('../../src/assets/images/girl1.png'),
  girl2: require('../../src/assets/images/girl2.jpeg'),
  flash: require('../../src/assets/images/flash.png'),
  refresh: require('../../src/assets/images/refresh.png'),
  heartbottom: require('../../src/assets/images/heartbottom.png'),
  righthand: require('../../src/assets/images/righthand.png'),
  lefthand: require('../../src/assets/images/lefthand.png'),
  border: require('../../src/assets/images/border.png'),
  closemodal: require('../../src/assets/images/closemodal.png'),
  whiteheart: require('../../src/assets/images/whiteheart.png'),
  selectheart: require('../../src/assets/images/selectheart.png'),
  selectbutton: require('../../src/assets/images/selectbutton.png'),
};

export default {
  ruhEsinImages,
};
